Tracker:AddLocations("locations/Afterlife.json")
Tracker:AddLocations("locations/Airship.json")
Tracker:AddLocations("locations/Arcade 1.json")
Tracker:AddLocations("locations/Arcade 2.json")
Tracker:AddLocations("locations/Arcade Island.json")
Tracker:AddLocations("locations/Drill Castle.json")
Tracker:AddLocations("locations/Foglast.json")
Tracker:AddLocations("locations/Hylemxylem.json")
Tracker:AddLocations("locations/Juice Ranch.json")
Tracker:AddLocations("locations/New Muldul.json")
Tracker:AddLocations("locations/Sage Airship.json")
Tracker:AddLocations("locations/Sage Labyrinth.json")
Tracker:AddLocations("locations/TV Island.json")
Tracker:AddLocations("locations/Viewax's Edifice.json")
Tracker:AddLocations("locations/Waynehouse.json")
Tracker:AddLocations("locations/Worm Pod.json")
Tracker:AddLocations("locations/Overworld.json")
